DROP TRIGGER trigger_city;
DROP TRIGGER trigger_program;
DROP TRIGGER ORDER_FRIEND_PAIRS;

DROP TABLE FRIENDS;
DROP TABLE USER_CURRENT_CITIES;
DROP TABLE USER_HOMETOWN_CITIES;
DROP TABLE EDUCATION;
DROP TABLE PROGRAMS;
DROP TABLE PARTICIPANTS;
DROP TABLE USER_EVENTS;
DROP TABLE CITIES;
DROP TABLE TAGS;
DROP TABLE PHOTOS CASCADE CONSTRAINTS;
DROP TABLE ALBUMS CASCADE CONSTRAINTS;
DROP TABLE MESSAGES;
DROP TABLE USERS;

DROP SEQUENCE city_seq;
DROP SEQUENCE program_seq;
