-- TEST VIEWS
SELECT COUNT(*)
FROM (
	SELECT * FROM project1.PUBLIC_PHOTO_information
	MINUS
	SELECT * FROM VIEW_PHOTO_INFORMATION 
);

SELECT COUNT(*)
FROM (
	SELECT * FROM VIEW_EVENT_INFORMATION
	MINUS
	SELECT * FROM project1.PUBLIC_EVENT_information
);

SELECT COUNT(*)  --NO ROWS
FROM (
	SELECT * FROM VIEW_USER_INFORMATION
	MINUS
	SELECT * FROM project1.PUBLIC_USER_information
);
SELECT COUNT(*)  --NOT NO ROWS
FROM (
	SELECT * FROM project1.PUBLIC_TAG_information
	MINUS
	SELECT * FROM VIEW_TAG_INFORMATION 
);

-- FRO VIEW_ARE_FRIENDS
SELECT LEAST(USER1_ID, USER2_ID), GREATEST(USER1_ID, USER2_ID)
FROM project1.PUBLIC_ARE_FRIENDS
MINUS
SELECT LEAST(USER1_ID, USER2_ID), GREATEST(USER1_ID, USER2_ID)
FROM VIEW_ARE_FRIENDS;

SELECT LEAST(USER1_ID, USER2_ID), GREATEST(USER1_ID, USER2_ID)
FROM VIEW_ARE_FRIENDS
MINUS
SELECT LEAST(USER1_ID, USER2_ID), GREATEST(USER1_ID, USER2_ID)
FROM project1.PUBLIC_ARE_FRIENDS;