SELECT C.COUNTRY_NAME, C.CITY_NAME, C.STATE_NAME
FROM CITIES C 
JOIN USER_CURRENT_CITIES UCC
ON C.CITY_ID = UCC.CITY_ID
WHERE 

SELECT F.USER2_ID
FROM PROJECT3.PUBLIC_USERS U
JOIN PROJECT3.PUBLIC_FRIENDS F
ON U.USER_ID = F.USER1_ID
WHERE U.USER_ID = 789

SELECT *
FROM PROJECT3.PUBLIC_USERS U 
LEFT JOIN PROJECT3.PUBLIC_USER_CURRENT_CITIES UCC 
ON U.USER_ID = UCC.USER_ID
JOIN PROJECT3.PUBLIC_CITIES C 
ON UCC.CURRENT_CITY_ID = C.CITY_ID
-- WHERE U.USER_ID = 653
WHERE UCC.CURRENT_CITY_ID IS NULL

SELECT *
FROM PROJECT3.PUBLIC_USERS U 
LEFT JOIN PROJECT3.PUBLIC_USER_HOMETOWN_CITIES UHC
ON U.USER_ID = UHC.USER_ID
WHERE UHC.HOMETOWN_CITY_ID IS NULL