SELECT DISTINCT P.PUBLISHER_ID, P.NAME
FROM EDITIONS E 
INNER JOIN PUBLISHERS P ON E.PUBLISHER_ID = P.PUBLISHER_ID
INNER JOIN BOOKS B ON E.BOOK_ID = B.BOOK_ID 
INNER JOIN AUTHORS A ON B.AUTHOR_ID = A.AUTHOR_ID
WHERE B.AUTHOR_ID IN (
	SELECT DISTINCT B.AUTHOR_ID
	FROM AUTHORS A
	INNER JOIN BOOKS B ON A.AUTHOR_ID = B.AUTHOR_ID 
	GROUP BY B.AUTHOR_ID 
	HAVING COUNT(DISTINCT B.BOOK_ID) = 3
) 
ORDER BY P.PUBLISHER_ID DESC ;
