SELECT DISTINCT B.TITLE, E.PUBLICATION_DATE, T1.AUTHOR_ID, A.FIRST_NAME, A.LAST_NAME 
FROM BOOKS B 
INNER JOIN EDITIONS E ON B.BOOK_ID = E.BOOK_ID 
INNER JOIN (
	SELECT DISTINCT B.AUTHOR_ID
	FROM BOOKS B 
	INNER JOIN (
		SELECT E.BOOK_ID
		FROM EDITIONS E
		WHERE E.PUBLICATION_DATE BETWEEN '2003-01-01' AND '2008-12-31' 
		GROUP BY E.BOOK_ID 
	)T ON B.BOOK_ID = T.BOOK_ID
)T1 ON B.AUTHOR_ID = T1.AUTHOR_ID
INNER JOIN AUTHORS A ON A.AUTHOR_ID = T1.AUTHOR_ID 
ORDER BY T1.AUTHOR_ID ASC, B.TITLE ASC, E.PUBLICATION_DATE DESC ;
