SELECT A.FIRST_NAME, A.LAST_NAME
FROM AUTHORS A, (
	SELECT A.AUTHOR_ID
	FROM AUTHORS A, BOOKS B, SUBJECTS S
	WHERE A.AUTHOR_ID = B.AUTHOR_ID AND S.SUBJECT_ID = B.SUBJECT_ID AND S.SUBJECT = 'Children/YA'
	GROUP BY A.AUTHOR_ID
	HAVING COUNT(*) >= 1
	INTERSECT
	SELECT A.AUTHOR_ID
	FROM AUTHORS A, BOOKS B, SUBJECTS S
	WHERE A.AUTHOR_ID = B.AUTHOR_ID AND S.SUBJECT_ID = B.SUBJECT_ID AND S.SUBJECT = 'Fiction'
	GROUP BY A.AUTHOR_ID
	HAVING COUNT(*) >= 1
) T
WHERE A.AUTHOR_ID = T.AUTHOR_ID
ORDER BY A.FIRST_NAME ASC, A.LAST_NAME ASC ;

