SELECT A.AUTHOR_ID, A.FIRST_NAME, A.LAST_NAME
FROM AUTHORS A 
WHERE NOT EXISTS(
	SELECT DISTINCT B.SUBJECT_ID
	FROM AUTHORS A1 
	INNER JOIN BOOKS B ON A1.AUTHOR_ID = B.AUTHOR_ID 
	WHERE A1.LAST_NAME = 'Rowling' AND A1.FIRST_NAME = 'J. K.'
	MINUS
	SELECT DISTINCT B.SUBJECT_ID
	FROM AUTHORS A2
	INNER JOIN BOOKS B ON A2.AUTHOR_ID = B.AUTHOR_ID
	WHERE A.AUTHOR_ID = A2.AUTHOR_ID
)
ORDER BY A.LAST_NAME ASC, A.AUTHOR_ID DESC;

-- SELECT A.AUTHOR_ID, A.FIRST_NAME, A.LAST_NAME
-- FROM AUTHORS A 
-- WHERE NOT EXISTS(
-- 	(SELECT DISTINCT B.SUBJECT_ID
-- 	FROM AUTHORS A1 
-- 	INNER JOIN BOOKS B ON A1.AUTHOR_ID = B.AUTHOR_ID 
-- 	WHERE A1.LAST_NAME = 'Rowling' AND A1.FIRST_NAME = 'J. K.')
-- 	MINUS
-- 	(SELECT DISTINCT B.SUBJECT_ID
-- 	FROM AUTHORS A2
-- 	INNER JOIN BOOKS B ON A2.AUTHOR_ID = B.AUTHOR_ID
-- 	WHERE A.AUTHOR_ID = A2.AUTHOR_ID)
-- )
-- ORDER BY A.LAST_NAME ASC, A.AUTHOR_ID DESC;