SELECT DISTINCT S.SID, S.NAME
FROM MEMBERS M1
INNER JOIN MEMBERS M2 ON M1.SID != M2.SID AND M1.PID = M2.PID 
INNER JOIN (
	SELECT DISTINCT E.SID AS SID
	FROM ENROLLMENTS E 
	INNER JOIN COURSES C ON E.CID = C.CID
	WHERE C.C_NAME = 'EECS482' OR C.C_NAME = 'EECS483'
	INTERSECT
	SELECT DISTINCT E.SID AS SID
	FROM ENROLLMENTS E 
	INNER JOIN COURSES C ON E.CID = C.CID
	WHERE C.C_NAME = 'EECS484' OR C.C_NAME = 'EECS485'
	INTERSECT
	SELECT DISTINCT E.SID AS SID
	FROM ENROLLMENTS E
	INNER JOIN COURSES C ON E.CID = C.CID 
	WHERE C.C_NAME = 'EECS280' 
) T ON M2.SID = T.SID
INNER JOIN STUDENTS S ON M1.SID = S.SID
ORDER BY S.NAME DESC;
