SELECT DISTINCT E.CID 
FROM ENROLLMENTS E
LEFT JOIN (
	SELECT SID
	FROM STUDENTS 
	WHERE MAJOR != 'CS' OR MAJOR IS NULL
) T ON E.SID = T.SID 
GROUP BY E.CID 
HAVING COUNT(T.SID) < 10 
ORDER BY E.CID DESC ;
