-- CREATE VIEW STUDENTPAIRS AS
-- SELECT E1,SID AS SID1, E2.SID AS SID2
-- FROM ENROLLMENTS E1, ENROLLMENTS E2
-- WHERE E1.SID < E2.SID AND E1.CID = E2.CID
-- GROUP BY E1.SID, E2.SID
-- HAVING COUNT(*) >= 1 AND (E1.SID, E2.SID) NOT IN (
-- 	SELECT M1.SID, M2.SID
-- 	FROM MEMBERS M1, MEMBERS M2
-- 	WHERE M1.SID < M2.SID AND M1.PID = M2.PID
-- );



-- CREATE VIEW STUDENTPAIRS AS
-- SELECT DISTINCT E1.SID AS SID1, E2.SID AS SID2
-- FROM ENROLLMENTS E1 
-- INNER JOIN ENROLLMENTS E2 ON E1.SID < E2.SID AND E1.CID = E2.CID 
-- INTERSECT 
-- SELECT DISTINCT M1.SID AS SID1, M2.SID AS SID2 
-- FROM MEMBERS M1 
-- INNER JOIN MEMBERS M2 ON M1.SID < M2.SID AND M1.PID != M2.PID ;


-- CREATE VIEW StudentPairs AS
-- SELECT DISTINCT E1.SID AS SID1, E2.SID AS SID2
-- FROM ENROLLMENTS E1 
-- INNER JOIN ENROLLMENTS E2 ON E1.SID < E2.SID AND E1.CID = E2.CID 
-- INNER JOIN MEMBERS M1 ON M1.SID = E1.SID
-- INNER JOIN MEMBERS M2 ON M2.SID = E2.SID
-- WHERE NOT EXISTS (
-- 	SELECT DISTINCT M3.PID
-- 	FROM MEMBERS M3
-- 	WHERE M3.SID = E1.SID
-- 	INTERSECT
-- 	SELECT DISTINCT M4.PID 
-- 	FROM MEMBERS M4
-- 	WHERE M4.SID = E2.SID
-- );

-- CREATE VIEW StudentPairs AS
-- SELECT DISTINCT S1.SID AS SID1, S2.SID AS SID2
-- FROM STUDENTS S1, STUDENTS S2, ENROLLMENTS E1, ENROLLMENTS E2 
-- WHERE S1.SID < S2.SID AND S1.SID = E1.SID AND S2.SID = E2.SID AND E1.CID = E2.CID
-- AND NOT EXISTS(
-- 	SELECT * 
-- 	FROM MEMBERS M1, MEMBERS M2 
-- 	WHERE M1.PID = M2.PID AND M1.SID = S1.SID AND M2.SID = S2.SID
-- );



CREATE VIEW StudentPairs AS
SELECT DISTINCT E1.SID AS SID1, E2.SID AS SID2
FROM ENROLLMENTS E1, ENROLLMENTS E2 
WHERE E1.SID < E2.SID AND E1.CID = E2.CID
AND NOT EXISTS(
	SELECT * 
	FROM MEMBERS M1, MEMBERS M2 
	WHERE M1.PID = M2.PID AND M1.SID = E1.SID AND M2.SID = E2.SID
);